default:
  image: ruby:3.2
  # 'Bundle' all the required gems for the project
  before_script:
    - gem install bundler
    - bundle install --path vendor
  # Add bundle cache to 'vendor' & untracked files for speeding up builds
  cache:
    paths: 
      - vendor/

# Add a workflow to force the pipeline to run only when changes are pushed to branches
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

# Build and deploy the site
create-pages:
  stage: deploy
  script: 
    - bundle exec jekyll build -d public
  # specifies that this is a Pages job and publishes the default public directory
  pages: true
  # specify on which branch this pipeline will run
  rules:
    - if: $CI_COMMIT_BRANCH == "pages"
  environment: production

