name: Rosie & Jim's Travel Blog
description: A blog of all our travels
owner: rosiejim
authors:
  - richard
  - rosie
url: http://travel.perry-online.me.uk
email: travel@perry-online.me.uk

exclude: 
  - 'changes'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Gruntfile.js'
  - 'node_modules'
  - 'package.json'
  - 'Rakefile'
  - 'README.md'
gems: 
  - jemoji
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

encoding: utf-8

permalink: /:categories/:title/
relative_permalinks: false

paginate: 10
paginate_path: "page/:num"
  
images: /assets/images
thumbs: /assets/images/thumbs

category_dir: /

# Location Config
locations:
  UK:
    name: UK
    link: /uk/
  Cornwall:
    name: Cornwall
    link: /uk/cornwall/
  North-East:
    name: North East England
    link: /uk/north-east/
  Vietnam: 
    name: Vietnam
    link: /vietnam/
  Hanoi:
    name: Hanoi
    link: /vietnam/hanoi/
  Ha-Long-Bay:
    name: Ha Long Bay
    link: /vietnam/ha-long-bay/
  Huế:
    name: Huế
    link: /vietnam/huế/
  Hội-An:
    name: "Hội-An"
    link: /vietnam/hội-an/
  Iceland:
    name: Iceland
    link: /iceland/
  Reykjavik:
    name: Reykjavik
    link: /iceland/reykjavik/
  

flickr:
  enabled:         yes
  cache_dir:       _cache/flickr
  screen_name:     Richard Perry
  api_key:         4389a0eb79c41ca17e149830c22fc7c2
  shared_secret:   ef41108edae962b0
  access_token:    72157641557984045-92a5dbebf3e01418
  access_secret:   1625dbdd3cf26db6
