source 'https://rubygems.org'
gem 'jekyll', '~> 2.4'
gem 'github-pages', '~> 43'
# gem 'stringex'
gem 'titleize'
gem 'jekyll-oembed', :require => 'jekyll_oembed'
gem 'flickraw'
gem 'emoji_for_jekyll'
gem 'execjs'
gem 'therubyracer', :platforms => :ruby
#gem 'jekyll-paginate'
#gem 'jekyll-sitemap'
#gem 'jekyll-gist'